In [ ]:
import numpy as np
"""1 – Crie
dois arrays NumPy: A = [10, 20, 30, 40, 50] e B = [1, 2, 3, 4, 5].  Realize as seguintes operações entre
eles:     

Soma
Subtração
Multiplicação
Divisão """

a = np.array([10,20,30,40,50])
b = np.array([1,2,3,4,5])
c = np.add(a,b)
d = np.subtract(a,b)
e = np.multiply(a,b)
f = np.divide(a,b)
print(f" A Soma é:---> {c}\n A Subtração é:--->{d}\n A Multiplicação é: --->{e}\n A divisão é:---> {f}")

 A Soma é:---> [11 22 33 44 55]
 A Subtração é:--->[ 9 18 27 36 45]
 A Multiplicação é: --->[ 10  40  90 160 250]
 A divisão é:---> [10. 10. 10. 10. 10.]


In [13]:
"""2 – Crie um array NumPy com os seguintes valores: [12, 15, 20, 25, 30, 35, 40].  Utilize funções NumPy para calcular:
Soma total
Média
Desvio padrão
Máximo e mínimo     
Imprima cada resultado com clareza."""

a = np.array([12,15,20,25,30,35,40])
b = np.sum(a)
c = np.mean(a)
d = np.std(a)
e = np.min(a)
f = np.max(a)

print(f"A soma de todos os elementos é: {b}\nA média de todos os elementos é: {c:.2f}\nO desvio padrão de todos os elementos é: {d:.2f}\nO elemento mínimo é: {e}\nO elemento máximo é: {f}")


A soma de todos os elementos é: 177
A média de todos os elementos é: 25.29
O desvio padrão de todos os elementos é: 9.59
O elemento mínimo é: 12
O elemento máximo é: 40


In [28]:
"""3 – Crie uma matriz NumPy (2x3): [[1, 2, 3], [4, 5, 6]] e então adicione o vetor [10, 20, 30] a cada linha da matriz usando broadcasting, multiplique a matriz resultante pelo escalar 2 e Imprima a matriz inicial, após soma e após
multiplicação."""

a = np.array([[1,2,3],[4,5,6]])
a= np.reshape(a,(2,3))
b=np.array([[1,2,3],[4,5,6],[10,20,30]])
c = np.sum(b)
d = c* 2
print(b)
print(c)
print(b)
print(d)

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]
81
[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]
162
