In [1]:
import numpy as np

a = np.array([1,2,3,4,5])
b = np.array([7,5,6,2.4])
print(a,b)
c = np.add(a,b)
print(c)
#array tem que ter a mesma quantidade de elementos
d = np.multiply(a,b)
print(d)

e = np.sqrt(a,b)
print(e)



[1 2 3 4 5] [7.  5.  6.  2.4]


ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [3]:
a =np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
a = np.array([1,2,3,])
b = np.array([[[1,2,3]],[[4,5,6]],[[7,8,9]]])
c= a+b
print(c)

[[[ 2  4  6]]

 [[ 5  7  9]]

 [[ 8 10 12]]]
